// by default all components in next.js are SERVER components
// turn into client component with directive: "use client";
// create new components on the leaves of the component tree
// use server components as much as possible and only add interactivity where needed
// bc that will keep your js bundle as small as possible --> perfomance better
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavMenu from "./NavMenu";
import AuthProvider from "./AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        // AuthProvider now gives us access to the current user
        // anywhere  in the client side application
        <AuthProvider> 
            <html lang="en">
                <body className={inter.className}>
                    <div>
                        <NavMenu />
                        <main>{children}</main>
                    </div>
                </body>
            </html>
        </AuthProvider>
    );
}
